#!/usr/bin/python3
# -*- coding: utf-8 -*-

from schedulerlib.scheduler import EventScheduler
from schedulerlib.constants import CONFIG, CONFIG_PATH, HOLIDAYS
import os
import sys
import logging
from tkinter import Tk
from tkinter.messagebox import showerror

# vérifie si mynotes est déjà lancé
pid = str(os.getpid())
pidfile = "/tmp/scheduler.pid"

if os.path.isfile(pidfile):
    with open(pidfile) as fich:
        old_pid = fich.read().strip()
    if os.path.exists("/proc/%s" % old_pid):
        # already runnning
        root = Tk()
        root.withdraw()
        showerror("Error", "Scheduler is already running. If not deletes /tmp/scheduler.pid")
        sys.exit()
    else:
        # it is an old pid file (certainly due to session logout then login)
        os.remove(pidfile)
open(pidfile, 'w').write(pid)
try:
    app = EventScheduler()
    if '--withdraw' not in sys.argv:
        app.deiconify()
    app.mainloop()
finally:
    try:
        app.save()
    except NameError:
        pass
    CONFIG.set('Calendar', 'holidays', ', '.join(HOLIDAYS))
    with open(CONFIG_PATH, 'w') as file:
        CONFIG.write(file)
    os.unlink(pidfile)
    logging.info('Quit')
