.TH "Scheduler" "1" "April 2019" "Scheduler 1.1.1" ""
.SH NAME
Scheduler \- Alarms and reminders
.SH SYNOPSIS
.B scheduler [ \fI\-\-withdraw\fR ]
.SH DESCRIPTION
System tray application for Linux to schedule events with possibity to set reminders. 
It also provides the following desktop widgets: a calendar to display and add events,
the list of the week's events, a list of tasks, a timer, a pomodoro timer recording statistics.
.SH AUTHOR
Scheduler is developped by Juliette Monsel <j_4321@protonmail.com>
.SH BUGS
Please submit bugs on the Github page of the project
\fBhttps://github.com/j4321/Scheduler/issues\fR.
