#!/usr/bin/python3
# -*- coding: utf-8 -*-

from schedulerlib.scheduler import EventScheduler
from schedulerlib.constants import CONFIG, CONFIG_PATH, HOLIDAYS, PIDFILE, save_config
import os
import sys
import logging
from tkinter import Tk
from tkinter.messagebox import showerror

# vérifie si mynotes est déjà lancé
pid = str(os.getpid())

if os.path.isfile(PIDFILE):
    with open(PIDFILE) as fich:
        old_pid = fich.read().strip()
    if os.path.exists("/proc/%s" % old_pid):
        # already runnning
        root = Tk()
        root.withdraw()
        showerror("Error", "Scheduler is already running. If not deletes ~/.scheduler/scheduler.pid")
        sys.exit()
    else:
        # it is an old pid file (certainly due to session logout then login)
        os.remove(PIDFILE)
open(PIDFILE, 'w').write(pid)
try:
    app = EventScheduler()
    if '--withdraw' not in sys.argv:
        app.deiconify()
    app.mainloop()
finally:
    try:
        app.save()
    except NameError:
        pass
    save_config()
    try:
        os.unlink(PIDFILE)
    except FileNotFoundError:
        # PIDFILE might have been deleted
        pass
    logging.info('Quit')
